name: CI

env:
    CI: true

on: [push]

jobs:
    build-test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.1'
                  extensions: gd
                  tools: composer, phpunit

            - name: Composer
              run: composer install --no-interaction

            - name: PHPUnit
              run: ./vendor/bin/phpunit
